"GET /checkout/ HTTP/1.1" 200 24314
"GET /checkout/ HTTP/1.1" 200 24314
"GET /static/css/checkout.css HTTP/1.1" 200 542
"GET /static/css/base.css HTTP/1.1" 200 10401
"GET /static/js/stripe_element.js HTTP/1.1" 200 1876
Not Found: /checkout/media/icons8-quill-pen-32.png
"GET /checkout/media/icons8-quill-pen-32.png HTTP/1.1" 404 4130
"GET /checkout/ HTTP/1.1" 200 24314
"GET /checkout/ HTTP/1.1" 200 24314
"GET /static/css/base.css HTTP/1.1" 200 10401
"GET /static/css/checkout.css HTTP/1.1" 200 542
"GET /static/js/stripe_element.js HTTP/1.1" 200 1876
Not Found: /checkout/media/icons8-quill-pen-32.png
"GET /checkout/media/icons8-quill-pen-32.png HTTP/1.1" 404 4130
"GET /checkout/ HTTP/1.1" 200 24314
"GET /static/css/checkout.css HTTP/1.1" 200 542
"GET /static/css/base.css HTTP/1.1" 200 10401
"GET /static/js/stripe_element.js HTTP/1.1" 200 1899
Not Found: /checkout/media/icons8-quill-pen-32.png
"GET /checkout/media/icons8-quill-pen-32.png HTTP/1.1" 404 4130
"GET /checkout/ HTTP/1.1" 200 24314
"GET /static/css/checkout.css HTTP/1.1" 200 542
"GET /static/css/base.css HTTP/1.1" 200 10401
"GET /static/js/stripe_element.js HTTP/1.1" 200 1877
Not Found: /checkout/media/icons8-quill-pen-32.png
"GET /checkout/media/icons8-quill-pen-32.png HTTP/1.1" 404 4130
"GET /checkout/ HTTP/1.1" 200 24314
"GET /static/css/checkout.css HTTP/1.1" 200 542
"GET /static/css/base.css HTTP/1.1" 200 10401
"GET /static/js/stripe_element.js HTTP/1.1" 200 1877
Not Found: /checkout/media/icons8-quill-pen-32.png
"GET /checkout/media/icons8-quill-pen-32.png HTTP/1.1" 404 4130
"GET /checkout/ HTTP/1.1" 200 24314
"GET /static/css/checkout.css HTTP/1.1" 200 542
"GET /static/css/base.css HTTP/1.1" 200 10401
"GET /static/js/stripe_element.js HTTP/1.1" 200 1899
Not Found: /checkout/media/icons8-quill-pen-32.png
"GET /checkout/media/icons8-quill-pen-32.png HTTP/1.1" 404 4130
/mnt/c/Users/likwi/OneDrive/Desktop/PROJS/Quill/quill/settings.py changed, reloading.
Watching for file changes with StatReloader
/mnt/c/Users/likwi/OneDrive/Desktop/PROJS/Quill/quill/settings.py changed, reloading.
Watching for file changes with StatReloader
"GET /checkout/ HTTP/1.1" 200 24314
"GET /static/css/checkout.css HTTP/1.1" 200 542
"GET /static/css/base.css HTTP/1.1" 200 10401
"GET /static/js/stripe_element.js HTTP/1.1" 200 1877
Not Found: /checkout/media/icons8-quill-pen-32.png
"GET /checkout/media/icons8-quill-pen-32.png HTTP/1.1" 404 4130
/mnt/c/Users/likwi/OneDrive/Desktop/PROJS/Quill/quill/settings.py changed, reloading.
Watching for file changes with StatReloader
"GET /checkout/ HTTP/1.1" 200 24314
"GET /static/css/checkout.css HTTP/1.1" 200 542
"GET /static/css/base.css HTTP/1.1" 200 10401
"GET /static/js/stripe_element.js HTTP/1.1" 200 1877
Not Found: /checkout/media/icons8-quill-pen-32.png
"GET /checkout/media/icons8-quill-pen-32.png HTTP/1.1" 404 4130
"GET /checkout/ HTTP/1.1" 200 24314
/mnt/c/Users/likwi/OneDrive/Desktop/PROJS/Quill/quill/settings.py changed, reloading.
Watching for file changes with StatReloader
"GET /checkout/ HTTP/1.1" 200 24530
"GET /static/css/checkout.css HTTP/1.1" 200 542
"GET /static/css/base.css HTTP/1.1" 200 10401
"GET /static/js/stripe_element.js HTTP/1.1" 200 1877
Not Found: /checkout/media/icons8-quill-pen-32.png
"GET /checkout/media/icons8-quill-pen-32.png HTTP/1.1" 404 4130
"GET /admin HTTP/1.1" 301 0
"GET /admin/ HTTP/1.1" 200 10371
"GET /static/admin/css/nav_sidebar.css HTTP/1.1" 200 2694
"GET /static/admin/css/dark_mode.css HTTP/1.1" 200 2929
"GET /static/admin/css/base.css HTTP/1.1" 200 21207
"GET /static/admin/css/dashboard.css HTTP/1.1" 200 441
"GET /static/admin/js/theme.js HTTP/1.1" 200 1943
"GET /static/admin/css/responsive.css HTTP/1.1" 200 18557
"GET /static/admin/js/nav_sidebar.js HTTP/1.1" 200 3063
"GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
"GET /static/admin/img/icon-no.svg HTTP/1.1" 200 560
"GET /static/admin/img/icon-yes.svg HTTP/1.1" 200 436
"GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 3562
"GET / HTTP/1.1" 200 11773
"GET /static/css/base.css HTTP/1.1" 200 10401
"GET /products/?category=crime-thriller HTTP/1.1" 200 23696
"GET /bag/ HTTP/1.1" 200 13305
Not Found: /bag/media/icons8-quill-pen-32.png
"GET /bag/media/icons8-quill-pen-32.png HTTP/1.1" 404 4273
"GET /checkout/ HTTP/1.1" 200 24530
"GET /static/css/checkout.css HTTP/1.1" 200 542
"GET /static/js/stripe_element.js HTTP/1.1" 200 1877
/mnt/c/Users/likwi/OneDrive/Desktop/PROJS/Quill/quill/settings.py changed, reloading.
Watching for file changes with StatReloader
/mnt/c/Users/likwi/OneDrive/Desktop/PROJS/Quill/quill/settings.py changed, reloading.
Watching for file changes with StatReloader
"GET /checkout/ HTTP/1.1" 200 24530
Not Found: /checkout/media/icons8-quill-pen-32.png
"GET /checkout/media/icons8-quill-pen-32.png HTTP/1.1" 404 4130
"POST /checkout/ HTTP/1.1" 302 0
"GET /checkout/checkout_success/367C5279331141F999F37729DC0CD174/ HTTP/1.1" 200 6434
Not Found: /checkout/checkout_success/367C5279331141F999F37729DC0CD174/media/icons8-quill-pen-32.png
"GET /checkout/checkout_success/367C5279331141F999F37729DC0CD174/media/icons8-quill-pen-32.png HTTP/1.1" 404 4280
/mnt/c/Users/likwi/OneDrive/Desktop/PROJS/Quill/quill/settings.py changed, reloading.
Watching for file changes with StatReloader
/mnt/c/Users/likwi/OneDrive/Desktop/PROJS/Quill/quill/settings.py changed, reloading.
Watching for file changes with StatReloader
/mnt/c/Users/likwi/OneDrive/Desktop/PROJS/Quill/quill/settings.py changed, reloading.
Watching for file changes with StatReloader
"GET /products/ HTTP/1.1" 200 24049
Not Found: /products/media/icons8-quill-pen-32.png
"GET /products/media/icons8-quill-pen-32.png HTTP/1.1" 404 4872
"POST /bag/add/2386/ HTTP/1.1" 302 0
"GET /products/ HTTP/1.1" 200 24049
"GET /products/3171/ HTTP/1.1" 200 13066
Not Found: /products/3171/media/icons8-quill-pen-32.png
"GET /products/3171/media/icons8-quill-pen-32.png HTTP/1.1" 404 4887
"GET /bag/ HTTP/1.1" 200 12038
Not Found: /bag/media/icons8-quill-pen-32.png
"GET /bag/media/icons8-quill-pen-32.png HTTP/1.1" 404 4273
"GET /checkout/ HTTP/1.1" 200 23790
"POST /checkout/ HTTP/1.1" 302 0
"GET /checkout/checkout_success/2B0CB4A3E3564E708929200102929190/ HTTP/1.1" 200 6434
Not Found: /checkout/checkout_success/2B0CB4A3E3564E708929200102929190/media/icons8-quill-pen-32.png
"GET /checkout/checkout_success/2B0CB4A3E3564E708929200102929190/media/icons8-quill-pen-32.png HTTP/1.1" 404 4280
"GET /admin/ HTTP/1.1" 200 10701
"GET /static/admin/img/icon-yes.svg HTTP/1.1" 200 436
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 3562
"GET /accounts/logout/ HTTP/1.1" 200 9420
Not Found: /accounts/logout/media/icons8-quill-pen-32.png
"GET /accounts/logout/media/icons8-quill-pen-32.png HTTP/1.1" 404 7250
"POST /accounts/logout/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 11464
"GET /accounts/login/ HTTP/1.1" 200 10323
Not Found: /accounts/login/media/icons8-quill-pen-32.png
"GET /accounts/login/media/icons8-quill-pen-32.png HTTP/1.1" 404 7247
"GET /accounts/signup/ HTTP/1.1" 200 11172
Not Found: /accounts/signup/media/icons8-quill-pen-32.png
"GET /accounts/signup/media/icons8-quill-pen-32.png HTTP/1.1" 404 7250
Internal Server Error: /accounts/signup/
Traceback (most recent call last):
  File "/home/gbemi/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/gbemi/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/gbemi/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/gbemi/.local/lib/python3.10/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/gbemi/.local/lib/python3.10/site-packages/allauth/decorators.py", line 12, in wrap
    resp = function(request, *args, **kwargs)
  File "/home/gbemi/.local/lib/python3.10/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/gbemi/.local/lib/python3.10/site-packages/django/views/decorators/debug.py", line 92, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/home/gbemi/.local/lib/python3.10/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/gbemi/.local/lib/python3.10/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/gbemi/.local/lib/python3.10/site-packages/allauth/account/views.py", line 255, in dispatch
    return super(SignupView, self).dispatch(request, *args, **kwargs)
  File "/home/gbemi/.local/lib/python3.10/site-packages/allauth/account/views.py", line 95, in dispatch
    response = super(RedirectAuthenticatedUserMixin, self).dispatch(
  File "/home/gbemi/.local/lib/python3.10/site-packages/allauth/account/views.py", line 227, in dispatch
    return super(CloseableSignupMixin, self).dispatch(request, *args, **kwargs)
  File "/home/gbemi/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/gbemi/.local/lib/python3.10/site-packages/allauth/account/views.py", line 123, in post
    response = self.form_valid(form)
  File "/home/gbemi/.local/lib/python3.10/site-packages/allauth/account/views.py", line 273, in form_valid
    return complete_signup(
  File "/home/gbemi/.local/lib/python3.10/site-packages/allauth/account/utils.py", line 241, in complete_signup
    return perform_login(
  File "/home/gbemi/.local/lib/python3.10/site-packages/allauth/account/utils.py", line 166, in perform_login
    return _perform_login(request, login)
  File "/home/gbemi/.local/lib/python3.10/site-packages/allauth/account/utils.py", line 176, in _perform_login
    response = adapter.pre_login(request, login.user, **hook_kwargs)
  File "/home/gbemi/.local/lib/python3.10/site-packages/allauth/account/adapter.py", line 464, in pre_login
    send_email_confirmation(request, user, signup=signup, email=email)
  File "/home/gbemi/.local/lib/python3.10/site-packages/allauth/account/utils.py", line 399, in send_email_confirmation
    email_address.send_confirmation(request, signup=signup)
  File "/home/gbemi/.local/lib/python3.10/site-packages/allauth/account/models.py", line 93, in send_confirmation
    confirmation.send(request, signup=signup)
  File "/home/gbemi/.local/lib/python3.10/site-packages/allauth/account/models.py", line 126, in send
    get_adapter().send_confirmation_mail(request, self, signup)
  File "/home/gbemi/.local/lib/python3.10/site-packages/allauth/account/adapter.py", line 641, in send_confirmation_mail
    self.send_mail(email_template, emailconfirmation.email_address.email, ctx)
  File "/home/gbemi/.local/lib/python3.10/site-packages/allauth/account/adapter.py", line 186, in send_mail
    msg.send()
  File "/home/gbemi/.local/lib/python3.10/site-packages/django/core/mail/message.py", line 298, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/home/gbemi/.local/lib/python3.10/site-packages/django/core/mail/backends/smtp.py", line 134, in send_messages
    sent = self._send(message)
  File "/home/gbemi/.local/lib/python3.10/site-packages/django/core/mail/backends/smtp.py", line 152, in _send
    self.connection.sendmail(
  File "/usr/lib/python3.10/smtplib.py", line 887, in sendmail
    raise SMTPSenderRefused(code, resp, from_addr)
smtplib.SMTPSenderRefused: (530, b'5.7.0 Authentication Required. For more information, go to\n5.7.0  https://support.google.com/mail/?p=WantAuthError o32-20020a05600c512000b004148a5e3188sm5696195wms.25 - gsmtp', 'quillstore4@gmail.com')
"POST /accounts/signup/ HTTP/1.1" 500 189796
"GET /admin/ HTTP/1.1" 302 0
"GET /admin/login/?next=/admin/ HTTP/1.1" 200 4307
"GET /static/admin/css/login.css HTTP/1.1" 200 958
/mnt/c/Users/likwi/OneDrive/Desktop/PROJS/Quill/checkout/views.py changed, reloading.
Watching for file changes with StatReloader
/mnt/c/Users/likwi/OneDrive/Desktop/PROJS/Quill/checkout/views.py changed, reloading.
Watching for file changes with StatReloader
/mnt/c/Users/likwi/OneDrive/Desktop/PROJS/Quill/checkout/views.py changed, reloading.
Watching for file changes with StatReloader
/mnt/c/Users/likwi/OneDrive/Desktop/PROJS/Quill/checkout/views.py changed, reloading.
Watching for file changes with StatReloader
/mnt/c/Users/likwi/OneDrive/Desktop/PROJS/Quill/checkout/views.py changed, reloading.
Watching for file changes with StatReloader
/mnt/c/Users/likwi/OneDrive/Desktop/PROJS/Quill/checkout/views.py changed, reloading.
Watching for file changes with StatReloader
/mnt/c/Users/likwi/OneDrive/Desktop/PROJS/Quill/checkout/views.py changed, reloading.
Watching for file changes with StatReloader
/mnt/c/Users/likwi/OneDrive/Desktop/PROJS/Quill/checkout/views.py changed, reloading.
Watching for file changes with StatReloader
/mnt/c/Users/likwi/OneDrive/Desktop/PROJS/Quill/checkout/views.py changed, reloading.
Watching for file changes with StatReloader
/mnt/c/Users/likwi/OneDrive/Desktop/PROJS/Quill/checkout/views.py changed, reloading.
Watching for file changes with StatReloader
/mnt/c/Users/likwi/OneDrive/Desktop/PROJS/Quill/checkout/views.py changed, reloading.
Watching for file changes with StatReloader
/mnt/c/Users/likwi/OneDrive/Desktop/PROJS/Quill/checkout/views.py changed, reloading.
Watching for file changes with StatReloader
/mnt/c/Users/likwi/OneDrive/Desktop/PROJS/Quill/checkout/views.py changed, reloading.
Watching for file changes with StatReloader
/mnt/c/Users/likwi/OneDrive/Desktop/PROJS/Quill/checkout/views.py changed, reloading.
Watching for file changes with StatReloader
/mnt/c/Users/likwi/OneDrive/Desktop/PROJS/Quill/checkout/views.py changed, reloading.
Watching for file changes with StatReloader
/mnt/c/Users/likwi/OneDrive/Desktop/PROJS/Quill/checkout/views.py changed, reloading.
Watching for file changes with StatReloader
/mnt/c/Users/likwi/OneDrive/Desktop/PROJS/Quill/checkout/views.py changed, reloading.
Watching for file changes with StatReloader
/mnt/c/Users/likwi/OneDrive/Desktop/PROJS/Quill/checkout/views.py changed, reloading.
Watching for file changes with StatReloader
/mnt/c/Users/likwi/OneDrive/Desktop/PROJS/Quill/checkout/views.py changed, reloading.
Watching for file changes with StatReloader
/mnt/c/Users/likwi/OneDrive/Desktop/PROJS/Quill/checkout/views.py changed, reloading.
Watching for file changes with StatReloader
/mnt/c/Users/likwi/OneDrive/Desktop/PROJS/Quill/checkout/views.py changed, reloading.
Watching for file changes with StatReloader
/mnt/c/Users/likwi/OneDrive/Desktop/PROJS/Quill/checkout/views.py changed, reloading.
Watching for file changes with StatReloader
"POST /accounts/signup/ HTTP/1.1" 200 11379
"GET /accounts/login/ HTTP/1.1" 200 10323
Internal Server Error: /accounts/login/
Traceback (most recent call last):
  File "/home/gbemi/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/gbemi/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/gbemi/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/gbemi/.local/lib/python3.10/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/gbemi/.local/lib/python3.10/site-packages/django/views/decorators/debug.py", line 92, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/home/gbemi/.local/lib/python3.10/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/gbemi/.local/lib/python3.10/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/gbemi/.local/lib/python3.10/site-packages/allauth/account/views.py", line 168, in dispatch
    return super(LoginView, self).dispatch(request, *args, **kwargs)
  File "/home/gbemi/.local/lib/python3.10/site-packages/allauth/account/views.py", line 95, in dispatch
    response = super(RedirectAuthenticatedUserMixin, self).dispatch(
  File "/home/gbemi/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/gbemi/.local/lib/python3.10/site-packages/allauth/account/views.py", line 123, in post
    response = self.form_valid(form)
  File "/home/gbemi/.local/lib/python3.10/site-packages/allauth/account/views.py", line 181, in form_valid
    return form.login(self.request, redirect_url=success_url)
  File "/home/gbemi/.local/lib/python3.10/site-packages/allauth/account/forms.py", line 210, in login
    ret = perform_login(
  File "/home/gbemi/.local/lib/python3.10/site-packages/allauth/account/utils.py", line 166, in perform_login
    return _perform_login(request, login)
  File "/home/gbemi/.local/lib/python3.10/site-packages/allauth/account/utils.py", line 176, in _perform_login
    response = adapter.pre_login(request, login.user, **hook_kwargs)
  File "/home/gbemi/.local/lib/python3.10/site-packages/allauth/account/adapter.py", line 464, in pre_login
    send_email_confirmation(request, user, signup=signup, email=email)
  File "/home/gbemi/.local/lib/python3.10/site-packages/allauth/account/utils.py", line 399, in send_email_confirmation
    email_address.send_confirmation(request, signup=signup)
  File "/home/gbemi/.local/lib/python3.10/site-packages/allauth/account/models.py", line 93, in send_confirmation
    confirmation.send(request, signup=signup)
  File "/home/gbemi/.local/lib/python3.10/site-packages/allauth/account/models.py", line 126, in send
    get_adapter().send_confirmation_mail(request, self, signup)
  File "/home/gbemi/.local/lib/python3.10/site-packages/allauth/account/adapter.py", line 641, in send_confirmation_mail
    self.send_mail(email_template, emailconfirmation.email_address.email, ctx)
  File "/home/gbemi/.local/lib/python3.10/site-packages/allauth/account/adapter.py", line 186, in send_mail
    msg.send()
  File "/home/gbemi/.local/lib/python3.10/site-packages/django/core/mail/message.py", line 298, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/home/gbemi/.local/lib/python3.10/site-packages/django/core/mail/backends/smtp.py", line 134, in send_messages
    sent = self._send(message)
  File "/home/gbemi/.local/lib/python3.10/site-packages/django/core/mail/backends/smtp.py", line 152, in _send
    self.connection.sendmail(
  File "/usr/lib/python3.10/smtplib.py", line 887, in sendmail
    raise SMTPSenderRefused(code, resp, from_addr)
smtplib.SMTPSenderRefused: (530, b'5.7.0 Authentication Required. For more information, go to\n5.7.0  https://support.google.com/mail/?p=WantAuthError a1-20020a05600c348100b004148dd74327sm2892851wmq.34 - gsmtp', 'quillstore4@gmail.com')
"POST /accounts/login/ HTTP/1.1" 500 175388
"GET /accounts/login/ HTTP/1.1" 200 10323
Internal Server Error: /accounts/login/
Traceback (most recent call last):
  File "/home/gbemi/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/gbemi/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/gbemi/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/gbemi/.local/lib/python3.10/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/gbemi/.local/lib/python3.10/site-packages/django/views/decorators/debug.py", line 92, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/home/gbemi/.local/lib/python3.10/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/gbemi/.local/lib/python3.10/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/gbemi/.local/lib/python3.10/site-packages/allauth/account/views.py", line 168, in dispatch
    return super(LoginView, self).dispatch(request, *args, **kwargs)
  File "/home/gbemi/.local/lib/python3.10/site-packages/allauth/account/views.py", line 95, in dispatch
    response = super(RedirectAuthenticatedUserMixin, self).dispatch(
  File "/home/gbemi/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/gbemi/.local/lib/python3.10/site-packages/allauth/account/views.py", line 123, in post
    response = self.form_valid(form)
  File "/home/gbemi/.local/lib/python3.10/site-packages/allauth/account/views.py", line 181, in form_valid
    return form.login(self.request, redirect_url=success_url)
  File "/home/gbemi/.local/lib/python3.10/site-packages/allauth/account/forms.py", line 210, in login
    ret = perform_login(
  File "/home/gbemi/.local/lib/python3.10/site-packages/allauth/account/utils.py", line 166, in perform_login
    return _perform_login(request, login)
  File "/home/gbemi/.local/lib/python3.10/site-packages/allauth/account/utils.py", line 176, in _perform_login
    response = adapter.pre_login(request, login.user, **hook_kwargs)
  File "/home/gbemi/.local/lib/python3.10/site-packages/allauth/account/adapter.py", line 464, in pre_login
    send_email_confirmation(request, user, signup=signup, email=email)
  File "/home/gbemi/.local/lib/python3.10/site-packages/allauth/account/utils.py", line 404, in send_email_confirmation
    email_address = EmailAddress.objects.add_email(
  File "/home/gbemi/.local/lib/python3.10/site-packages/allauth/account/managers.py", line 58, in add_email
    email_address.send_confirmation(request, signup=signup)
  File "/home/gbemi/.local/lib/python3.10/site-packages/allauth/account/models.py", line 93, in send_confirmation
    confirmation.send(request, signup=signup)
  File "/home/gbemi/.local/lib/python3.10/site-packages/allauth/account/models.py", line 126, in send
    get_adapter().send_confirmation_mail(request, self, signup)
  File "/home/gbemi/.local/lib/python3.10/site-packages/allauth/account/adapter.py", line 641, in send_confirmation_mail
    self.send_mail(email_template, emailconfirmation.email_address.email, ctx)
  File "/home/gbemi/.local/lib/python3.10/site-packages/allauth/account/adapter.py", line 186, in send_mail
    msg.send()
  File "/home/gbemi/.local/lib/python3.10/site-packages/django/core/mail/message.py", line 298, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/home/gbemi/.local/lib/python3.10/site-packages/django/core/mail/backends/smtp.py", line 134, in send_messages
    sent = self._send(message)
  File "/home/gbemi/.local/lib/python3.10/site-packages/django/core/mail/backends/smtp.py", line 152, in _send
    self.connection.sendmail(
  File "/usr/lib/python3.10/smtplib.py", line 887, in sendmail
    raise SMTPSenderRefused(code, resp, from_addr)
smtplib.SMTPSenderRefused: (530, b'5.7.0 Authentication Required. For more information, go to\n5.7.0  https://support.google.com/mail/?p=WantAuthError by19-20020a056000099300b0033e7eba040dsm13003267wrb.97 - gsmtp', 'quillstore4@gmail.com')
"POST /accounts/login/ HTTP/1.1" 500 179909
Watching for file changes with StatReloader
"GET /admin/login/?next=/admin/ HTTP/1.1" 200 4181
"GET /admin/login/?next=/admin/ HTTP/1.1" 200 4181
Internal Server Error: /accounts/login/
Traceback (most recent call last):
  File "/home/gbemi/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/gbemi/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/gbemi/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/gbemi/.local/lib/python3.10/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/gbemi/.local/lib/python3.10/site-packages/django/views/decorators/debug.py", line 92, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/home/gbemi/.local/lib/python3.10/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/gbemi/.local/lib/python3.10/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/gbemi/.local/lib/python3.10/site-packages/allauth/account/views.py", line 168, in dispatch
    return super(LoginView, self).dispatch(request, *args, **kwargs)
  File "/home/gbemi/.local/lib/python3.10/site-packages/allauth/account/views.py", line 95, in dispatch
    response = super(RedirectAuthenticatedUserMixin, self).dispatch(
  File "/home/gbemi/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/gbemi/.local/lib/python3.10/site-packages/allauth/account/views.py", line 123, in post
    response = self.form_valid(form)
  File "/home/gbemi/.local/lib/python3.10/site-packages/allauth/account/views.py", line 181, in form_valid
    return form.login(self.request, redirect_url=success_url)
  File "/home/gbemi/.local/lib/python3.10/site-packages/allauth/account/forms.py", line 210, in login
    ret = perform_login(
  File "/home/gbemi/.local/lib/python3.10/site-packages/allauth/account/utils.py", line 166, in perform_login
    return _perform_login(request, login)
  File "/home/gbemi/.local/lib/python3.10/site-packages/allauth/account/utils.py", line 176, in _perform_login
    response = adapter.pre_login(request, login.user, **hook_kwargs)
  File "/home/gbemi/.local/lib/python3.10/site-packages/allauth/account/adapter.py", line 464, in pre_login
    send_email_confirmation(request, user, signup=signup, email=email)
  File "/home/gbemi/.local/lib/python3.10/site-packages/allauth/account/utils.py", line 399, in send_email_confirmation
    email_address.send_confirmation(request, signup=signup)
  File "/home/gbemi/.local/lib/python3.10/site-packages/allauth/account/models.py", line 93, in send_confirmation
    confirmation.send(request, signup=signup)
  File "/home/gbemi/.local/lib/python3.10/site-packages/allauth/account/models.py", line 126, in send
    get_adapter().send_confirmation_mail(request, self, signup)
  File "/home/gbemi/.local/lib/python3.10/site-packages/allauth/account/adapter.py", line 641, in send_confirmation_mail
    self.send_mail(email_template, emailconfirmation.email_address.email, ctx)
  File "/home/gbemi/.local/lib/python3.10/site-packages/allauth/account/adapter.py", line 186, in send_mail
    msg.send()
  File "/home/gbemi/.local/lib/python3.10/site-packages/django/core/mail/message.py", line 298, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/home/gbemi/.local/lib/python3.10/site-packages/django/core/mail/backends/smtp.py", line 134, in send_messages
    sent = self._send(message)
  File "/home/gbemi/.local/lib/python3.10/site-packages/django/core/mail/backends/smtp.py", line 152, in _send
    self.connection.sendmail(
  File "/usr/lib/python3.10/smtplib.py", line 887, in sendmail
    raise SMTPSenderRefused(code, resp, from_addr)
smtplib.SMTPSenderRefused: (530, b'5.7.0 Authentication Required. For more information, go to\n5.7.0  https://support.google.com/mail/?p=WantAuthError s8-20020a5d69c8000000b0033e206a0a7asm12838864wrw.26 - gsmtp', 'quillstore4@gmail.com')
"POST /accounts/login/ HTTP/1.1" 500 175065
/mnt/c/Users/likwi/OneDrive/Desktop/PROJS/Quill/quill/settings.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /accounts/login/
Traceback (most recent call last):
  File "/home/gbemi/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/gbemi/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/gbemi/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/gbemi/.local/lib/python3.10/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/gbemi/.local/lib/python3.10/site-packages/django/views/decorators/debug.py", line 92, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/home/gbemi/.local/lib/python3.10/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/gbemi/.local/lib/python3.10/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/gbemi/.local/lib/python3.10/site-packages/allauth/account/views.py", line 168, in dispatch
    return super(LoginView, self).dispatch(request, *args, **kwargs)
  File "/home/gbemi/.local/lib/python3.10/site-packages/allauth/account/views.py", line 95, in dispatch
    response = super(RedirectAuthenticatedUserMixin, self).dispatch(
  File "/home/gbemi/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/gbemi/.local/lib/python3.10/site-packages/allauth/account/views.py", line 123, in post
    response = self.form_valid(form)
  File "/home/gbemi/.local/lib/python3.10/site-packages/allauth/account/views.py", line 181, in form_valid
    return form.login(self.request, redirect_url=success_url)
  File "/home/gbemi/.local/lib/python3.10/site-packages/allauth/account/forms.py", line 210, in login
    ret = perform_login(
  File "/home/gbemi/.local/lib/python3.10/site-packages/allauth/account/utils.py", line 166, in perform_login
    return _perform_login(request, login)
  File "/home/gbemi/.local/lib/python3.10/site-packages/allauth/account/utils.py", line 176, in _perform_login
    response = adapter.pre_login(request, login.user, **hook_kwargs)
  File "/home/gbemi/.local/lib/python3.10/site-packages/allauth/account/adapter.py", line 464, in pre_login
    send_email_confirmation(request, user, signup=signup, email=email)
  File "/home/gbemi/.local/lib/python3.10/site-packages/allauth/account/utils.py", line 399, in send_email_confirmation
    email_address.send_confirmation(request, signup=signup)
  File "/home/gbemi/.local/lib/python3.10/site-packages/allauth/account/models.py", line 93, in send_confirmation
    confirmation.send(request, signup=signup)
  File "/home/gbemi/.local/lib/python3.10/site-packages/allauth/account/models.py", line 126, in send
    get_adapter().send_confirmation_mail(request, self, signup)
  File "/home/gbemi/.local/lib/python3.10/site-packages/allauth/account/adapter.py", line 641, in send_confirmation_mail
    self.send_mail(email_template, emailconfirmation.email_address.email, ctx)
  File "/home/gbemi/.local/lib/python3.10/site-packages/allauth/account/adapter.py", line 186, in send_mail
    msg.send()
  File "/home/gbemi/.local/lib/python3.10/site-packages/django/core/mail/message.py", line 298, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/home/gbemi/.local/lib/python3.10/site-packages/django/core/mail/backends/smtp.py", line 134, in send_messages
    sent = self._send(message)
  File "/home/gbemi/.local/lib/python3.10/site-packages/django/core/mail/backends/smtp.py", line 152, in _send
    self.connection.sendmail(
  File "/usr/lib/python3.10/smtplib.py", line 887, in sendmail
    raise SMTPSenderRefused(code, resp, from_addr)
smtplib.SMTPSenderRefused: (530, b'5.7.0 Authentication Required. For more information, go to\n5.7.0  https://support.google.com/mail/?p=WantAuthError t13-20020a5d42cd000000b0033ec312cd8asm12938927wrr.33 - gsmtp', 'quillstore4@gmail.com')
"POST /accounts/login/ HTTP/1.1" 500 175069
Watching for file changes with StatReloader
"GET /accounts/login/ HTTP/1.1" 200 10323
"POST /accounts/login/ HTTP/1.1" 302 0
"GET /accounts/confirm-email/ HTTP/1.1" 200 8808
Not Found: /accounts/confirm-email/media/icons8-quill-pen-32.png
"GET /accounts/confirm-email/media/icons8-quill-pen-32.png HTTP/1.1" 404 7271
"GET /accounts/confirm-email/ HTTP/1.1" 200 8808
"GET / HTTP/1.1" 200 11464
"GET /accounts/login/ HTTP/1.1" 200 10323
"POST /accounts/login/ HTTP/1.1" 302 0
"GET /accounts/confirm-email/ HTTP/1.1" 200 8808
/mnt/c/Users/likwi/OneDrive/Desktop/PROJS/Quill/quill/settings.py changed, reloading.
Watching for file changes with StatReloader
/mnt/c/Users/likwi/OneDrive/Desktop/PROJS/Quill/quill/settings.py changed, reloading.
Watching for file changes with StatReloader
/mnt/c/Users/likwi/OneDrive/Desktop/PROJS/Quill/quill/settings.py changed, reloading.
Watching for file changes with StatReloader
/mnt/c/Users/likwi/OneDrive/Desktop/PROJS/Quill/quill/settings.py changed, reloading.
Watching for file changes with StatReloader
/mnt/c/Users/likwi/OneDrive/Desktop/PROJS/Quill/quill/settings.py changed, reloading.
Watching for file changes with StatReloader
